### ISSUE TITLE
Next time merge pull requests faster?

### ISSUE THREAD

**Issue by rugk** [HammiKnuff/34C3-Screen-Stuff#37]
Next time a bit more monitoring the PRs may be good, would not it?

Or just use the same images as the the official infobeamer at https://34c3.infobeamer.com/.

**Comment by HammiKnuff** [comment]
sorry! i had to do it all alone. and i got sick :(

**Comment by rugk** [comment]
Oh too bad, sorry for you. I'm sure many of us would have helped (including myself).

So as for the next time: would not you also prefer to use the same images of the infobeamer or is there any reason why it is separated?
