### ISSUE TITLE
QR code has no quiet zone

### ISSUE THREAD

**Issue by The-Compiler** [HammiKnuff/34C3-Screen-Stuff#5]
The QR code linking to this repo on the screens does not have a [quiet zone](https://qrworld.wordpress.com/2011/08/09/the-quiet-zone/) around it, so with the (quite popular, I think) [ZXing](https://github.com/zxing/zxing) Android app I was unable to scan it.

**Comment by jonasbits** [comment]
Qrafter on iOS also fails to read this qr

**Comment by HammiKnuff** [comment]
thanks. next version on the screen will have that now!
